PKGNAME := Unicode-LineBreak
PKGVER := 2017.004
PKGSRC := $(PKGNAME)-$(PKGVER).tar.gz
PKGSRCDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)
PATCHLIST := $(PATCHDB)/$(PKGNAME)/list.txt
PATCHDIR := $(PATCHDB)/$(PKGNAME)
SRCURL := http://search.cpan.org/CPAN/authors/id/N/NE/NEZUMI/Unicode-LineBreak-2017.004.tar.gz
PKGOBJDIR := $(TCBUILDROOT)/$(PKGNAME)-obj
