PKGNAME := IO-Compress
PKGVER := 2.068
PKGSRC := $(PKGNAME)-$(PKGVER).tar.gz
PKGSRCDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)
PATCHLIST := $(PATCHDB)/$(PKGNAME)/list.txt
PATCHDIR := $(PATCHDB)/$(PKGNAME)
PKGOBJDIR := $(TCBUILDROOT)/$(PKGNAME)-obj
