PKGNAME := libmusicbrainz
PKGVER := 5.1.0
PKGSRC := $(PKGNAME)-$(PKGVER).tar.gz
PKGSRCDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)
PKGOBJDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)-obj
PKGOBJDIR-HOST := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)-host-obj
PATCHLIST := $(PATCHDB)/$(PKGNAME)5/list.txt
PATCHDIR := $(PATCHDB)/$(PKGNAME)5
SRCURL := https://github.com/metabrainz/$(PKGNAME)/releases/download/release-5.1.0/$(PKGSRC)

HOST_CC := gcc
HOST_CXX := g++

HOST-COPTS := -D CMAKE_INSTALL_PREFIX=/usr \
	-D CMAKE_C_COMPILER=$(HOST_CC) \
	-D CMAKE_CXX_COMPILER=$(HOST_CXX)

TARGET-COPTS := -D BUILD_SHARED_LIBS=ON \
	-D CMAKE_CROSSCOMPILING=1 \
	-D CMAKE_SYSTEM_NAME=Linux \
	-D CMAKE_BUILD_TYPE=Release \
	-D CMAKE_INSTALL_PREFIX=/usr \
	-D LIB_INSTALL_DIR:PATH=lib \
	-D CMAKE_FIND_ROOT_PATH=$(SYSROOTDIR) \
	-D CMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
	-D CMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
	-D CMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
	-D CMAKE_LINKER=$(CROSSTOOLS)/bin/"${LD}" \
	-D CMAKE_C_COMPILER_AR=$(CROSSTOOLS)/bin/"${AR}" \
	-D CMAKE_C_COMPILER_RANLIB=$(CROSSTOOLS)/bin/"${RANLIB}" \
	-D IMPORT_EXECUTABLES=$(PKGOBJDIR-HOST)/ImportExecutables.cmake

ifeq ($(ARCH),arm)
        COPTS := $(COPTS) \
		-D CMAKE_SYSTEM_PROCESSOR=arm
endif

ifeq ($(ARCH),aarch64)
        COPTS := $(COPTS) \
		-D CMAKE_SYSTEM_PROCESSOR=aarch64
endif

ifeq ($(ARCH),x86_64)
        COPTS := $(COPTS) \
		-D CMAKE_SYSTEM_PROCESSOR=x86_64
endif

CC := "${CC}"
CXX := "${CXX}"

PKGDIR := $(PKGDB)/$(PKGNAME)5
ORIGSRC := $(PKGNAME)_$(PKGVER).orig.tar.xz
PKGROOT := $(DISTRIBROOT)/$(PKGNAME)5
DISTRIBSRC := $(PKGROOT)/$(PKGNAME)-$(PKGVER)
PKGBINDIR := $(DISTRIBSRC)/debian/pkg
