PKGNAME := msgpack
PKGVER := 2.1.5
PKGSRC := cpp-$(PKGVER).tar.gz
PKGSRCDIR := $(TCBUILDROOT)/$(PKGNAME)-c-cpp-$(PKGVER)
PKGOBJDIR := $(TCBUILDROOT)/$(PKGNAME)-c-cpp-$(PKGVER)-obj
PATCHLIST := $(PATCHDB)/$(PKGNAME)/list.txt
PATCHDIR := $(PATCHDB)/$(PKGNAME)
SRCURL := https://github.com/msgpack/msgpack-c/archive/cpp-$(PKGVER).tar.gz
COPTS := -D CMAKE_INSTALL_PREFIX=/usr \
	-D CMAKE_LINKER=$(CROSSTOOLS)/bin/"${LD}" \
	-D CMAKE_C_COMPILER_AR=$(CROSSTOOLS)/bin/"${AR}" \
	-D CMAKE_C_COMPILER_RANLIB=$(CROSSTOOLS)/bin/"${RANLIB}" \
	-D CMAKE_BUILD_TYPE=Release \
	-D MSGPACK_ENABLE_CXX=ON \
	-D MSGPACK_CXX11=ON \
	-D MSGPACK_BUILD_EXAMPLES=OFF \
	-D CMAKE_FIND_ROOT_PATH=$(SYSROOTDIR) \
	-D CMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
	-D CMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
	-D CMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY

ifeq ($(ARCH),arm)
	COPTS := $(COPTS) \
		-D CMAKE_CROSSCOMPILING=1 \
		-D CMAKE_SYSTEM_NAME=Linux \
		-D CMAKE_SYSTEM_PROCESSOR=arm
endif

ifeq ($(ARCH),x86_64)
	COPTS := $(COPTS) \
		-D CMAKE_CROSSCOMPILING=1 \
		-D CMAKE_SYSTEM_NAME=Linux \
		-D CMAKE_SYSTEM_PROCESSOR=x86_64
endif

CC := "${CC} "
CXX := "${CXX} "
