PKGNAME := iproute2
PKGVER := 4.13.0
PKGSRC := $(PKGNAME)-$(PKGVER).tar.xz
PKGSRCDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)
PKGOBJDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)-obj
PATCHLIST := $(PATCHDB)/$(PKGNAME)/list.txt
PATCHDIR := $(PATCHDB)/$(PKGNAME)
SRCURL := https://www.kernel.org/pub/linux/utils/net/$(PKGNAME)/$(PKGSRC)
COPTS := 
CC := "${CC} "
HOSTCC := gcc
DBMINCLUDE := $(SYSROOTDIR)/usr/include
