PKGNAME := Sys-Hostname-Long
PKGVER := 1.5
PKGSRC := $(PKGNAME)-$(PKGVER).tar.gz
PKGSRCDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)
PATCHLIST := $(PATCHDB)/$(PKGNAME)/list.txt
PATCHDIR := $(PATCHDB)/$(PKGNAME)
PKGOBJDIR := $(TCBUILDROOT)/$(PKGNAME)-obj
