PKGNAME := zip
PKGVER := 30
PKGSRC := $(PKGNAME)$(PKGVER).tar.gz
PKGSRCDIR := $(TCBUILDROOT)/$(PKGNAME)$(PKGVER)
PKGOBJDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)-obj
PATCHLIST := $(PATCHDB)/$(PKGNAME)/list.txt
PATCHDIR := $(PATCHDB)/$(PKGNAME)
SRCURL := https://downloads.sourceforge.net/infozip/$(PKGSRC)
COPTS :=

CC := "${CC}"

CPPFLAGS := -I. -DUNIX -O3 \
	-DBZIP2_SUPPORT \
	-DUIDGID_NOT_16BIT \
	-DLARGE_FILE_SUPPORT \
	-DUNICODE_SUPPORT

PKGDIR := $(PKGDB)/$(PKGNAME)
ORIGSRC := $(PKGNAME)_$(PKGVER).orig.tar.xz
PKGROOT := $(DISTRIBROOT)/$(PKGNAME)
DISTRIBSRC := $(PKGROOT)/$(PKGNAME)-$(PKGVER)
PKGBINDIR := $(DISTRIBSRC)/debian/pkg
