PKGNAME := Mail-Sendmail
PKGVER := 0.79_16
PKGSRC := $(PKGNAME)-$(PKGVER).tar.gz
PKGSRCDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)
PATCHLIST := $(PATCHDB)/$(PKGNAME)/list.txt
PATCHDIR := $(PATCHDB)/$(PKGNAME)
PKGOBJDIR := $(TCBUILDROOT)/$(PKGNAME)-obj
