##########################################################################
# 
# Filename: config.x86_64.inc
#
# Purpose: x86_64 cpu config
#
# Copyright (c) 2007 - 2018 Mwanguhya Daniel Murungi <tuxmason@gmail.com>
#
#########################################################################

# CPU Architecture 
# (read doc/cpu_arch.txt)
ARCH := x86_64

# Target Processor family
# ( read doc/target_processor.txt )
PROC := x86_64

# 64-bit target
BUILD64 := -m64

