##########################################################################
# 
# Filename: Makefile.config 
#
# Purpose: 
# 	- generates cross toolchain 'environment' configuration
#
# Copyright (c) 2010 - 2017 Mwanguhya Daniel Murungi <tuxmason@gmail.com>
#
#########################################################################

# Absolute path configuration 
APP := zinja
RELEASE := 0.0.1-pre-alpha
TOPDIR := $(shell pwd)
TOP := $(shell dirname $(TOPDIR))
SRCDIR := $(TOPDIR)/sources
PATCHDIR := $(TOPDIR)/patches
PATCHDB := $(TOPDIR)/patchdb
SCRIPTSDIR := $(TOPDIR)/scripts
TCBUILDROOT := $(TOPDIR)/build
PKGLOGDIR := "$(TCBUILDROOT)/build-logs"
TIMELOG := "$(PKGLOGDIR)/build-time.log"
MANDIR := $(TCBUILDROOT)/manpages
INFODIR := $(TCBUILDROOT)/infopages
DOCDIR := $(TCBUILDROOT)/docs
DATE := $(shell date -R)
CONF := $(TOPDIR)/conf/environment.mk

# Installation Directory
SYSROOTDIR := $(TOPDIR)/sysroot

DESTDIR := $(SYSROOTDIR)

# HOST Path
HOSTPATH := $(shell echo ${PATH})

#set root password to random string if password has not been set
ifeq ($(ROOTPASSWD),)
	ROOTPASSWD := $(shell < /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c8)
endif

#packaging
PKGDB := $(TOPDIR)/pkgdb
DISTRIBROOT := $(TOPDIR)/distrib
PKGADMINDIR := $(SYSROOTDIR)/var/lib/dpkg

# Repository
REPOROOT := $(TOPDIR)/apt-repo
DISTSROOT := $(REPOROOT)/dists

#set default timezone
ifeq ($(TIMEZONE),)
	TIMEZONE := Africa/Dar_es_Salaam
endif

# If vendor string is empty, set VENDOR to pc if architecture is x86 and unknown 
# if architecture is x86_64
ifeq ($(VENDOR),)
   ifeq ($(ARCH),$(filter $(ARCH),x86_64 arm aarch64))
     VENDOR := unknown
   else
     VENDOR := pc
   endif
endif

# set REVISION to "current date"-001 if revision string is empty
ifeq ($(REVISION),)
	REVISION := $(shell date +"%Y-%m-%d")-001
endif

# Use all CPU cores for the build process if user specifies automatic CPU core 
# discovery else, use one CPU core
ifeq ($(MULTICORE),auto)
	NPROCS := $(shell cat /proc/cpuinfo | grep processor | wc -l )
else
	NPROCS := 1
endif

# set target triplet suffix based on C library (default == musl)
ifeq ($(LIBC),uClibc)
     TSUFFIX := uclibc
   else
     TSUFFIX := musl
endif

# host triplet
HOSTARCH := $(shell echo $$MACHTYPE | sed -e 's/-[^-]*/-cross/')

# build triplet
BUILDARCH := $(HOSTARCH)

# arch specific config
ifeq ($(ARCH),x86_64)
	TPROC := x86_64
	PKGARCH := musl-linux-amd64
	CROSSTOOLS := $(TOPDIR)/cross-tools.$(ARCH)
	# set the target triplet
	TARGETARCH := $(ARCH)-linux-$(TSUFFIX)
else ifeq ($(ARCH),arm)
	PKGARCH := musl-linux-armhf# Debian arch name
	CROSSTOOLS := $(TOPDIR)/cross-tools.$(ARCH)
	TPROC := $(shell echo $(CPU_ARCH_TYPE) | sed -e 's/-//')
	# set the target triplet
	ifeq ($(FLOAT),hard)
		TARGETARCH := $(ARCH)-linux-$(TSUFFIX)eabihf
	else
		TARGETARCH := $(ARCH)-linux-$(TSUFFIX)eabi
	endif
else ifeq ($(ARCH),aarch64)
	TPROC := $(ARCH)
	PKGARCH := musl-linux-arm64
	CROSSTOOLS := $(TOPDIR)/cross-tools.$(ARCH)
	TARGETARCH := $(ARCH)-linux-$(TSUFFIX)
endif

ifeq ($(ARCH),x86)
	TPROC := $(CPU_ARCH_TYPE)
endif

# Build Path
PATH := $(CROSSTOOLS)/bin:/usr/bin:/bin


base-dirs:
	@if [ ! -d $(DISTRIBROOT) ]; then mkdir -p $(DISTRIBROOT); fi
	@if [ ! -d $(TCBUILDROOT) ]; then mkdir -p $(TCBUILDROOT); fi
	@if [ ! -d $(SYSROOTDIR) ]; then mkdir -p $(SYSROOTDIR); fi
	@if [ ! -d $(CROSSTOOLS) ]; then mkdir -p $(CROSSTOOLS); fi
	@if [ ! -d $(PKGLOGDIR) ]; then mkdir -p $(PKGLOGDIR); fi

config: base-dirs
	@if [ -f $(CONF) ]; then echo "Run 'make clean' to remove existing configuration"; exit 1; fi
	@echo "ARCH := $(ARCH)" >> $(CONF)
	@echo "PKGARCH := $(PKGARCH)" >> $(CONF)
ifeq ($(ARCH),arm)
	@echo "ARCH_TYPE := $(CPU_ARCH_TYPE)" >> $(CONF)
	@echo "ABI := $(ABI)" >> $(CONF)
	@echo "ENDIAN := $(ENDIAN)" >> $(CONF)
	@echo "ARM_MODE := $(ARM_MODE)" >> $(CONF)
	@echo "FLOAT := $(FLOAT)" >> $(CONF)
	@echo "FPU := $(FPU)" >> $(CONF)
endif
ifeq ($(ARCH),aarch64)
	@echo "ARCH_TYPE := $(CPU_ARCH_TYPE)" >> $(CONF)
	@echo "ENDIAN := $(ENDIAN)" >> $(CONF)
	@echo "ARM_MODE := $(ARM_MODE)" >> $(CONF)
endif
	@echo "TPROC := $(TPROC)" >> $(CONF)
	@echo "VENDOR := $(VENDOR)" >> $(CONF)
	@echo "NPROCS := $(NPROCS)" >> $(CONF)
ifeq ($(ARCH),$(filter $(ARCH),x86_64 aarch64))
	@echo "BUILD64 := $(BUILD64)" >> $(CONF)
endif
	@echo "REVISION := $(REVISION)" >> $(CONF)
	@echo "ROOTPASSWD := $(ROOTPASSWD)" >> $(CONF)
	@echo "SYSROOTDIR := $(SYSROOTDIR)" >> $(CONF)
	@echo "DESTDIR := $(DESTDIR)" >> $(CONF)
	@echo "CROSSTOOLS := $(CROSSTOOLS)" >> $(CONF)
	@echo "TOP := $(TOP)" >> $(CONF)
	@echo "PATH := $(PATH)" >> $(CONF)
	@echo "HOSTPATH := $(HOSTPATH)" >> $(CONF)
	@echo "TOPDIR := $(TOPDIR)" >> $(CONF)
	@echo "SRCDIR := $(SRCDIR)" >> $(CONF)
	@echo "PATCHDIR := $(PATCHDIR)" >> $(CONF)
	@echo "PATCHDB := $(PATCHDB)" >> $(CONF)
	@echo "PKGDB := $(PKGDB)" >> $(CONF)
	@echo "PKGADMINDIR := $(PKGADMINDIR)" >> $(CONF)
	@echo "SCRIPTSDIR := $(SCRIPTSDIR)" >> $(CONF)
	@echo "DISTRIBROOT := $(DISTRIBROOT)" >> $(CONF)
	@echo "TCBUILDROOT := $(TCBUILDROOT)" >> $(CONF)
	@echo "PKGLOGDIR := $(PKGLOGDIR)" >> $(CONF)
	@echo "TIMELOG := $(TIMELOG)" >> $(CONF)
	@echo "MANDIR := $(MANDIR)" >> $(CONF)
	@echo "INFODIR := $(INFODIR)" >> $(CONF)
	@echo "DOCDIR := $(DOCDIR)" >> $(CONF)
	@echo "DATE := $(DATE)" >> $(CONF)
	@echo "TIMEZONE := $(TIMEZONE)" >> $(CONF)
	@echo "TARGETARCH := $(TARGETARCH)" >> $(CONF)
	@echo "HOSTARCH := $(HOSTARCH)" >> $(CONF)
	@echo "BUILDARCH := $(BUILDARCH)" >> $(CONF)
