PKGNAME := uClibc
PKGVER := master
PKGSRC := $(PKGNAME)-$(PKGVER).tar.xz
PKGSRCDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)
PKGOBJDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)-obj
PATCHLIST := $(PATCHDB)/$(PKGNAME)/list.txt
CONFIG := $(PATCHDB)/$(PKGNAME)/config.arm
PATCHDIR := $(PATCHDB)/$(PKGNAME)
