PKGNAME := uClibc
PKGVER := 0.9.33.2
PKGSRC := $(PKGNAME)-$(PKGVER).tar.xz
PKGSRCDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)
PKGOBJDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)-obj
PATCHLIST := $(PATCHDB)/$(PKGNAME)/list.txt
CONFIG := $(PATCHDB)/$(PKGNAME)/config.arm
PATCHDIR := $(PATCHDB)/$(PKGNAME)
