PKGNAME := freeglut
PKGVER := 3.0.0
PKGSRC := $(PKGNAME)-$(PKGVER).tar.gz
PKGSRCDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)
PKGOBJDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)-obj
PATCHLIST := $(PATCHDB)/$(PKGNAME)/list.txt
PATCHDIR := $(PATCHDB)/$(PKGNAME)
SRCURL := https://downloads.sourceforge.net/freeglut/$(PKGSRC)
COPTS := -D BUILD_SHARED_LIBS=ON \
	-D CMAKE_BUILD_TYPE=Release \
	-D CMAKE_INSTALL_PREFIX=/usr \
	-D CMAKE_INSTALL_SYSCONFDIR=/etc \
	-D FREEGLUT_BUILD_DEMOS=OFF \
	-D CMAKE_LINKER=$(CROSSTOOLS)/bin/"${LD}" \
	-D CMAKE_C_COMPILER_AR=$(CROSSTOOLS)/bin/"${AR}" \
	-D CMAKE_C_COMPILER_RANLIB=$(CROSSTOOLS)/bin/"${RANLIB}" \
	-D CMAKE_FIND_ROOT_PATH=$(SYSROOTDIR) \
	-D CMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
	-D CMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
	-D CMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY

ifeq ($(ARCH),arm)
        COPTS := $(COPTS) \
		-D CMAKE_CROSSCOMPILING=1 \
		-D CMAKE_SYSTEM_NAME=Linux \
		-D CMAKE_SYSTEM_PROCESSOR=arm
endif

ifeq ($(ARCH),x86_64)
        COPTS := $(COPTS) \
		-D CMAKE_CROSSCOMPILING=1 \
		-D CMAKE_SYSTEM_NAME=Linux \
		-D CMAKE_SYSTEM_PROCESSOR=x86_64
endif

CC := "${CC} "
CXX := "${CXX} "
