PKGNAME := freeglut
PKGVER := 3.0.0
PKGSRC := $(PKGNAME)-$(PKGVER).tar.gz
PKGSRCDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)
PKGOBJDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)-obj
PATCHLIST := $(PATCHDB)/$(PKGNAME)/list.txt
PATCHDIR := $(PATCHDB)/$(PKGNAME)
CMAKEOPTS := -DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_VERBOSE_MAKEFILE=ON \
	-DFREEGLUT_BUILD_DEMOS=OFF \
	-DCMAKE_TOOLCHAIN_FILE=$(PATCHDB)/shared/env.cmake

CC := "${CC} "
CXX := "${CXX} "
