PKGNAME := glew
PKGVER := 1.13.0
PKGSRC := $(PKGNAME)-$(PKGVER).tgz
PKGSRCDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)
PKGOBJDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)-obj
PATCHLIST := $(PATCHDB)/$(PKGNAME)/list.txt
PATCHDIR := $(PATCHDB)/$(PKGNAME)
COPTS := 

CC := "${CC}"
CXX := "${CXX}"
LD := $(CC) 
STRIP := "${STRIP}"
CFLAGS := "$$CFLAGS -fPIC"
