PKGNAME := exiv2
PKGVER := 0.26
PKGSRC := $(PKGNAME)-$(PKGVER)-trunk.tar.gz
PKGSRCDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)
PKGOBJDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)-obj
PATCHLIST := $(PATCHDB)/$(PKGNAME)/list.txt
PATCHDIR := $(PATCHDB)/$(PKGNAME)
SRCURL := http://www.exiv2.org/builds/$(PKGSRC)
COPTS := -D BUILD_SHARED_LIBS=ON \
	-D EXIV2_ENABLE_SSH=yes \
	-D EXIV2_ENABLE_CURL=yes \
	-D CMAKE_CROSSCOMPILING=1 \
	-D EXIV2_ENABLE_VIDEO=yes \
	-D CMAKE_SYSTEM_NAME=Linux \
	-D CMAKE_BUILD_TYPE=Release \
	-D EXIV2_ENABLE_WEBREADY=yes \
	-D CMAKE_INSTALL_PREFIX=/usr \
	-D EXIV2_ENABLE_BUILD_SAMPLES=no \
	-D CMAKE_INSTALL_SYSCONFDIR=/etc \
	-D CMAKE_FIND_ROOT_PATH=$(SYSROOTDIR) \
	-D CMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
	-D CMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
	-D CMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
	-D CMAKE_LINKER=$(CROSSTOOLS)/bin/"${LD}" \
	-D CMAKE_C_COMPILER_AR=$(CROSSTOOLS)/bin/"${AR}" \
	-D CMAKE_C_COMPILER_RANLIB=$(CROSSTOOLS)/bin/"${RANLIB}"

ifeq ($(ARCH),arm)
        COPTS := $(COPTS) \
		-D CMAKE_SYSTEM_PROCESSOR=arm
endif

ifeq ($(ARCH),x86_64)
        COPTS := $(COPTS) \
		-D CMAKE_SYSTEM_PROCESSOR=x86_64
endif

ifeq ($(ARCH),aarch64)
        COPTS := $(COPTS) \
		-D CMAKE_SYSTEM_PROCESSOR=aarch64
endif

CC := "${CC}"
CXX := "${CXX}"

PKGDIR := $(PKGDB)/$(PKGNAME)
ORIGSRC := $(PKGNAME)_$(PKGVER).orig.tar.xz
PKGROOT := $(DISTRIBROOT)/$(PKGNAME)
DISTRIBSRC := $(PKGROOT)/$(PKGNAME)-$(PKGVER)
PKGBINDIR := $(DISTRIBSRC)/debian/pkg
