PKGNAME := mariadb
PKGVER := 10.2.12
PKGSRC := $(PKGNAME)-$(PKGVER).tar.gz
LZ4VER := 1.8.1.2
LZ4SRC := lz4-$(LZ4VER).tar.gz
PKGSRCDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)
HOST_PKGOBJDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)-host-obj
TARGET_PKGOBJDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)-target-obj
PATCHLIST := $(PATCHDB)/$(PKGNAME)/list.txt
PATCHDIR := $(PATCHDB)/$(PKGNAME)
SRCURL := http://mirror.edatel.net.co/mariadb/$(PKGNAME)-$(PKGVER)/source/$(PKGSRC)

HOST_COPTS := -D SKIP_TESTS=ON \
	-D WITH_UNIT_TESTS=0 \
	-D WITH_JEMALLOC=no \
	-D WITH_EMBEDDED_SERVER=ON \
	-D WITH_EXTRA_CHARSETS=complex \
	-D CMAKE_BUILD_TYPE=Release \
	-D WITH_READLINE=ON \
	-D WITH_ZLIB=system \
	-D WITH_SSL=OFF \
	-D WITH_LIBWRAP=OFF \
	-D WITH_MROONGA=0 \
	-D PLUGIN_TOKUDB=NO \
	-D WITHOUT_XTRADB=1 \
	-D WITHOUT_BOOST=1 \
	-D ENABLE_DTRACE=0 \
	-D CONNECT_WITH_JDBC=0 \
	-D CONNECT_WITH_ODBC=0 \
	-D MONGO_ENABLED=0 \
	-D WITH_INNODB_SNAPPY=OFF \
	-D WITH_INNODB_LZO=OFF \
	-D WITH_INNODB_LZ4=OFF \
	-D GRN_WITH_BUNDLED_LZ4=ON \
	-D WITH_ARCHIVE_STORAGE_ENGINE=0 \
	-D WITH_INNOBASE_STORAGE_ENGINE=1 \
	-D WITH_BLACKHOLE_STORAGE_ENGINE=0 \
	-D WITH_PARTITION_STORAGE_ENGINE=0

TARGET_COPTS := -D SKIP_TESTS=ON \
	-D WITH_UNIT_TESTS=0 \
	-D STACK_DIRECTION=1 \
	-D WITH_JEMALLOC=no \
	-D WITH_EMBEDDED_SERVER=ON \
	-D WITH_EXTRA_CHARSETS=complex \
	-D CMAKE_INSTALL_PREFIX=/usr \
	-D INSTALL_MANDIR=share/man \
	-D INSTALL_SBINDIR=sbin \
	-D INSTALL_SCRIPTDIR=bin \
	-D MYSQL_DATADIR=/srv/mysql \
	-D IMPORT_EXECUTABLES=$(HOST_PKGOBJDIR)/import_executables.cmake \
	-D INSTALL_MYSQLSHAREDIR=share/mysql \
	-D INSTALL_PLUGINDIR=lib/mysql/plugin \
	-D INSTALL_SUPPORTFILESDIR=share/mysql \
	-D INSTALL_MYSQLTESTDIR=share/mysql/test \
	-D INSTALL_SQLBENCHDIR=share/mysql/bench \
	-D MYSQL_UNIX_ADDR=/run/mysqld/mysqld.sock \
	-D INSTALL_DOCDIR=share/doc/$(PKGNAME)-$(PKGVER) \
	-D INSTALL_DOCREADMEDIR=share/doc/$(PKGNAME)-$(PKGVER) \
	-D CMAKE_BUILD_TYPE=Release \
	-D WITH_READLINE=ON \
	-D WITH_ZLIB=system \
	-D WITH_SSL=system \
	-D WITH_LIBWRAP=OFF \
	-D WITH_MROONGA=1 \
	-D PLUGIN_TOKUDB=NO \
	-D WITHOUT_XTRADB=1 \
	-D WITHOUT_BOOST=1 \
	-D ENABLE_DTRACE=0 \
	-D CONNECT_WITH_JDBC=0 \
	-D CONNECT_WITH_ODBC=0 \
	-D MONGO_ENABLED=0 \
	-D WITH_INNODB_SNAPPY=ON \
	-D WITH_INNODB_LZO=ON \
	-D WITH_INNODB_LZ4=ON \
	-D WITH_ARCHIVE_STORAGE_ENGINE=1 \
	-D WITH_BLACKHOLE_STORAGE_ENGINE=1 \
	-D WITH_INNOBASE_STORAGE_ENGINE=1 \
	-D WITH_PARTITION_STORAGE_ENGINE=1 \
	-D HAVE_IB_GCC_ATOMIC_BUILTINS=1 \
	-D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
	-D CMAKE_LINKER=$(CROSSTOOLS)/bin/"${LD}" \
	-D CMAKE_C_COMPILER_AR=$(CROSSTOOLS)/bin/"${AR}" \
	-D CMAKE_C_COMPILER_RANLIB=$(CROSSTOOLS)/bin/"${RANLIB}" \
	-D CMAKE_FIND_ROOT_PATH=$(SYSROOTDIR) \
	-D CMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
	-D CMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
	-D CMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
	-D HAVE_UCONTEXT_H:INTERNAL=0 \
	-D GRN_WITH_BUNDLED_LZ4=ON

ifeq ($(ARCH),arm)
	TARGET_COPTS := $(TARGET_COPTS) \
	-D CMAKE_CROSSCOMPILING=1 \
	-D CMAKE_SYSTEM_NAME=Linux \
	-D CMAKE_SYSTEM_PROCESSOR=arm
endif

ifeq ($(ARCH),x86_64)
	TARGET_COPTS := $(TARGET_COPTS) \
	-D CMAKE_CROSSCOMPILING=1 \
	-D CMAKE_SYSTEM_NAME=Linux \
	-D CMAKE_SYSTEM_PROCESSOR=x86_64
endif

HOST_CC := gcc
HOST_CXX := g++

TARGET_CC := "${CC}"
TARGET_CXX := "${CXX}"

PKGDIR := $(PKGDB)/$(PKGNAME)
ORIGSRC := $(PKGNAME)_$(PKGVER).orig.tar.xz
PKGROOT := $(DISTRIBROOT)/$(PKGNAME)
DISTRIBSRC := $(PKGROOT)/$(PKGNAME)-$(PKGVER)
PKGBINDIR := $(DISTRIBSRC)/debian/pkg
