PKGNAME := apt
PKGVER := 1.4.8
PKGSRC := $(PKGNAME)_$(PKGVER).tar.xz
PKGSRCDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)
PKGOBJDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)-obj
PATCHLIST := $(PATCHDB)/$(PKGNAME)/list.txt
PATCHDIR := $(PATCHDB)/$(PKGNAME)
SRCURL := http://ftp.debian.org/debian/pool/main/a/$(PKGNAME)/$(PKGSRC)
COPTS := -D WITH_DOC=OFF \
	-D USE_NLS=OFF \
	-D CMAKE_INSTALL_PREFIX=$(CROSSTOOLS) \
	-D CMAKE_BUILD_TYPE=Release

HOST_CC := "gcc"
HOST_CXX := "g++"
