PKGNAME := nss
PKGVER := 3.34.1
PKGSRC := $(PKGNAME)-$(PKGVER).tar.gz
PKGSRCDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)
PKGOBJDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)-obj
PATCHLIST := $(PATCHDB)/$(PKGNAME)/list.txt
PATCHDIR := $(PATCHDB)/$(PKGNAME)
SRCURL := https://archive.mozilla.org/pub/security/nss/releases/NSS_3_34_1_RTM/src/$(PKGSRC)
COPTS := 
CC := "${CC} "
CXX := "${CXX} "
HOST_CC := gcc
