PKGNAME := sqlite
PKGVER := 3210000
PKGSRC := $(PKGNAME)-autoconf-$(PKGVER).tar.gz
PKGSRCDIR := $(TCBUILDROOT)/$(PKGNAME)-autoconf-$(PKGVER)
PKGOBJDIR := $(TCBUILDROOT)/$(PKGNAME)-autoconf-$(PKGVER)-obj
PATCHLIST := $(PATCHDB)/$(PKGNAME)/list.txt
PATCHDIR := $(PATCHDB)/$(PKGNAME)
COPTS := --prefix=/usr \
	--enable-readline \
	--build=$(BUILDARCH) \
	--host=$(TARGETARCH) \
	--enable-threadsafe 

CC := "${CC}"
CXX := "${CXX}"
CFLAGS := "-g -O2 -DSQLITE_ENABLE_FTS3=1 \
	-DSQLITE_ENABLE_COLUMN_METADATA=1 \
	-DSQLITE_ENABLE_UNLOCK_NOTIFY=1 \
	-DSQLITE_SECURE_DELETE=1 \
	-DSQLITE_ENABLE_DBSTAT_VTAB=1"

PKGDIR := $(PKGDB)/$(PKGNAME)3
ORIGSRC := $(PKGNAME)_$(PKGVER).orig.tar.xz
PKGROOT := $(DISTRIBROOT)/$(PKGNAME)3
DISTRIBSRC := $(PKGROOT)/$(PKGNAME)-autoconf-$(PKGVER)
PKGBINDIR := $(DISTRIBSRC)/debian/pkg
