PKGNAME := unzip
PKGVER := 60
PKGSRC := $(PKGNAME)$(PKGVER).tar.gz
PKGSRCDIR := $(TCBUILDROOT)/$(PKGNAME)$(PKGVER)
PKGOBJDIR := $(TCBUILDROOT)/$(PKGNAME)-$(PKGVER)-obj
PATCHLIST := $(PATCHDB)/$(PKGNAME)/list.txt
PATCHDIR := $(PATCHDB)/$(PKGNAME)
SRCURL := https://downloads.sourceforge.net/infozip/$(PKGSRC)
COPTS :=

CC := "${CC}"

AR := "${AR}"
RANLIB := "${RANLIB}"
LDFLAGS := -lc -lbz2

CPPFLAGS := -I. -Ibzip2 -DUNIX -O3 \
	-DLARGE_FILE_SUPPORT -DUNICODE_SUPPORT \
	-DUNICODE_WCHAR -DUNICODE_SUPPORT -DUTF8_MAYBE_NATIVE -DNO_LCHMOD

PKGDIR := $(PKGDB)/$(PKGNAME)
ORIGSRC := $(PKGNAME)_$(PKGVER).orig.tar.xz
PKGROOT := $(DISTRIBROOT)/$(PKGNAME)
DISTRIBSRC := $(PKGROOT)/$(PKGNAME)-$(PKGVER)
PKGBINDIR := $(DISTRIBSRC)/debian/pkg
